### ISSUE TITLE
Create function name and arguments and breaks off

### ISSUE THREAD

**Issue by espiat** [rosswintle/wpai#1]
i created the following files:
../wp-content/mu-plugins/wpai.php with this code 

then i created a testplugin (not mu)
added the following code:

```
/** 
Plugin Name: WP AI Code Companion
Plugin URI:
Description: A plugin to help you write code for your WordPress site.
Author: me
Author URI: https://domain.de
Version: 0.1.0
 */

// This is a stupid idea. Don't use this plugin.

add_action('init', 'wpai_test_init');

function wpai_test_init()
{

    //  if class wpai not exists
    if (class_exists('WPAI')) {


        //  make crazy stuff
        WPAI::register_recipe_post_type();
    }
}
```

and then i get this error:
![image](https://user-images.githubusercontent.com/6573582/228175434-b38e1d96-a881-491e-aa74-487b9afee1e2.png)

the api is calling. i can see the request in "last used" in chat gpt api overview

**Comment by espiat** [comment]
With included debug mode:

Initializing plugin...Loading funcs file...Creating funcs file...Calling function add_is_awesome_to_all_these_stringsCalling new function add_is_awesome_to_all_these_stringsError: Not Found

**Comment by rosswintle** [comment]
Thanks for reporting this. I think it's probably because OpenAI deprecated the language model I was using, and so I just need to swap that for another.

I'll take a look now and see if I can quickly fix it for you.

**Comment by espiat** [comment]
cUrl Error:

Initializing plugin...Loading funcs file...Creating funcs file...Calling function register_recipe_post_typeCalling new function register_recipe_post_typeError: cURL error 28: Operation timed out after 20009 milliseconds with 0 bytes received

**Comment by rosswintle** [comment]
Increase the timeout on line 218!

Anyway, I told you not to run it!! 😂

(This is pretty experimental code. Just for fun/experimenting. Feel free to fork it and improve it.)

**Comment by espiat** [comment]
oh works. i mean it does not work, because DONT run it.

**Comment by rosswintle** [comment]
No. Don't run it because it's dangerous!

Increasing the timeout should fix it.

But this is really just a fun experiment. Don't take it too seriously.
